// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/ivan-penchev/manga-updates/internal/domain"
)

// NotifierMock is an autogenerated mock type for the Notifier type
type NotifierMock struct {
	mock.Mock
}

type NotifierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NotifierMock) EXPECT() *NotifierMock_Expecter {
	return &NotifierMock_Expecter{mock: &_m.Mock}
}

// NotifyForNewChapter provides a mock function with given fields: ctx, chapter, fromManga
func (_m *NotifierMock) NotifyForNewChapter(ctx context.Context, chapter domain.ChapterEntity, fromManga domain.MangaEntity) error {
	ret := _m.Called(ctx, chapter, fromManga)

	if len(ret) == 0 {
		panic("no return value specified for NotifyForNewChapter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChapterEntity, domain.MangaEntity) error); ok {
		r0 = rf(ctx, chapter, fromManga)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifierMock_NotifyForNewChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyForNewChapter'
type NotifierMock_NotifyForNewChapter_Call struct {
	*mock.Call
}

// NotifyForNewChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - chapter domain.ChapterEntity
//   - fromManga domain.MangaEntity
func (_e *NotifierMock_Expecter) NotifyForNewChapter(ctx interface{}, chapter interface{}, fromManga interface{}) *NotifierMock_NotifyForNewChapter_Call {
	return &NotifierMock_NotifyForNewChapter_Call{Call: _e.mock.On("NotifyForNewChapter", ctx, chapter, fromManga)}
}

func (_c *NotifierMock_NotifyForNewChapter_Call) Run(run func(ctx context.Context, chapter domain.ChapterEntity, fromManga domain.MangaEntity)) *NotifierMock_NotifyForNewChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChapterEntity), args[2].(domain.MangaEntity))
	})
	return _c
}

func (_c *NotifierMock_NotifyForNewChapter_Call) Return(_a0 error) *NotifierMock_NotifyForNewChapter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifierMock_NotifyForNewChapter_Call) RunAndReturn(run func(context.Context, domain.ChapterEntity, domain.MangaEntity) error) *NotifierMock_NotifyForNewChapter_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifierMock creates a new instance of NotifierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotifierMock {
	mock := &NotifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
