// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ivan-penchev/manga-updates/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderRouter creates a new instance of MockProviderRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderRouter {
	mock := &MockProviderRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderRouter is an autogenerated mock type for the ProviderRouter type
type MockProviderRouter struct {
	mock.Mock
}

type MockProviderRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderRouter) EXPECT() *MockProviderRouter_Expecter {
	return &MockProviderRouter_Expecter{mock: &_m.Mock}
}

// GetProvider provides a mock function for the type MockProviderRouter
func (_mock *MockProviderRouter) GetProvider(manga domain.MangaEntity) (domain.Provider, error) {
	ret := _mock.Called(manga)

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 domain.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.MangaEntity) (domain.Provider, error)); ok {
		return returnFunc(manga)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.MangaEntity) domain.Provider); ok {
		r0 = returnFunc(manga)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Provider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.MangaEntity) error); ok {
		r1 = returnFunc(manga)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderRouter_GetProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvider'
type MockProviderRouter_GetProvider_Call struct {
	*mock.Call
}

// GetProvider is a helper method to define mock.On call
//   - manga domain.MangaEntity
func (_e *MockProviderRouter_Expecter) GetProvider(manga interface{}) *MockProviderRouter_GetProvider_Call {
	return &MockProviderRouter_GetProvider_Call{Call: _e.mock.On("GetProvider", manga)}
}

func (_c *MockProviderRouter_GetProvider_Call) Run(run func(manga domain.MangaEntity)) *MockProviderRouter_GetProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.MangaEntity
		if args[0] != nil {
			arg0 = args[0].(domain.MangaEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProviderRouter_GetProvider_Call) Return(provider domain.Provider, err error) *MockProviderRouter_GetProvider_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockProviderRouter_GetProvider_Call) RunAndReturn(run func(manga domain.MangaEntity) (domain.Provider, error)) *MockProviderRouter_GetProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderForURL provides a mock function for the type MockProviderRouter
func (_mock *MockProviderRouter) GetProviderForURL(url string) (domain.Provider, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderForURL")
	}

	var r0 domain.Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.Provider, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.Provider); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Provider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderRouter_GetProviderForURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderForURL'
type MockProviderRouter_GetProviderForURL_Call struct {
	*mock.Call
}

// GetProviderForURL is a helper method to define mock.On call
//   - url string
func (_e *MockProviderRouter_Expecter) GetProviderForURL(url interface{}) *MockProviderRouter_GetProviderForURL_Call {
	return &MockProviderRouter_GetProviderForURL_Call{Call: _e.mock.On("GetProviderForURL", url)}
}

func (_c *MockProviderRouter_GetProviderForURL_Call) Run(run func(url string)) *MockProviderRouter_GetProviderForURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProviderRouter_GetProviderForURL_Call) Return(provider domain.Provider, err error) *MockProviderRouter_GetProviderForURL_Call {
	_c.Call.Return(provider, err)
	return _c
}

func (_c *MockProviderRouter_GetProviderForURL_Call) RunAndReturn(run func(url string) (domain.Provider, error)) *MockProviderRouter_GetProviderForURL_Call {
	_c.Call.Return(run)
	return _c
}
