// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivan-penchev/manga-updates/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// GetLatestVersionMangaEntity provides a mock function for the type MockProvider
func (_mock *MockProvider) GetLatestVersionMangaEntity(ctx context.Context, manga domain.MangaEntity) (*domain.MangaEntity, error) {
	ret := _mock.Called(ctx, manga)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersionMangaEntity")
	}

	var r0 *domain.MangaEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MangaEntity) (*domain.MangaEntity, error)); ok {
		return returnFunc(ctx, manga)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MangaEntity) *domain.MangaEntity); ok {
		r0 = returnFunc(ctx, manga)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MangaEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.MangaEntity) error); ok {
		r1 = returnFunc(ctx, manga)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetLatestVersionMangaEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersionMangaEntity'
type MockProvider_GetLatestVersionMangaEntity_Call struct {
	*mock.Call
}

// GetLatestVersionMangaEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - manga domain.MangaEntity
func (_e *MockProvider_Expecter) GetLatestVersionMangaEntity(ctx interface{}, manga interface{}) *MockProvider_GetLatestVersionMangaEntity_Call {
	return &MockProvider_GetLatestVersionMangaEntity_Call{Call: _e.mock.On("GetLatestVersionMangaEntity", ctx, manga)}
}

func (_c *MockProvider_GetLatestVersionMangaEntity_Call) Run(run func(ctx context.Context, manga domain.MangaEntity)) *MockProvider_GetLatestVersionMangaEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.MangaEntity
		if args[1] != nil {
			arg1 = args[1].(domain.MangaEntity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_GetLatestVersionMangaEntity_Call) Return(mangaEntity *domain.MangaEntity, err error) *MockProvider_GetLatestVersionMangaEntity_Call {
	_c.Call.Return(mangaEntity, err)
	return _c
}

func (_c *MockProvider_GetLatestVersionMangaEntity_Call) RunAndReturn(run func(ctx context.Context, manga domain.MangaEntity) (*domain.MangaEntity, error)) *MockProvider_GetLatestVersionMangaEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetMangaFromURL provides a mock function for the type MockProvider
func (_mock *MockProvider) GetMangaFromURL(ctx context.Context, url string) (domain.MangaEntity, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetMangaFromURL")
	}

	var r0 domain.MangaEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.MangaEntity, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.MangaEntity); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(domain.MangaEntity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetMangaFromURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMangaFromURL'
type MockProvider_GetMangaFromURL_Call struct {
	*mock.Call
}

// GetMangaFromURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockProvider_Expecter) GetMangaFromURL(ctx interface{}, url interface{}) *MockProvider_GetMangaFromURL_Call {
	return &MockProvider_GetMangaFromURL_Call{Call: _e.mock.On("GetMangaFromURL", ctx, url)}
}

func (_c *MockProvider_GetMangaFromURL_Call) Run(run func(ctx context.Context, url string)) *MockProvider_GetMangaFromURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_GetMangaFromURL_Call) Return(mangaEntity domain.MangaEntity, err error) *MockProvider_GetMangaFromURL_Call {
	_c.Call.Return(mangaEntity, err)
	return _c
}

func (_c *MockProvider_GetMangaFromURL_Call) RunAndReturn(run func(ctx context.Context, url string) (domain.MangaEntity, error)) *MockProvider_GetMangaFromURL_Call {
	_c.Call.Return(run)
	return _c
}

// IsNewerVersionAvailable provides a mock function for the type MockProvider
func (_mock *MockProvider) IsNewerVersionAvailable(ctx context.Context, manga domain.MangaEntity) (bool, error) {
	ret := _mock.Called(ctx, manga)

	if len(ret) == 0 {
		panic("no return value specified for IsNewerVersionAvailable")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MangaEntity) (bool, error)); ok {
		return returnFunc(ctx, manga)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MangaEntity) bool); ok {
		r0 = returnFunc(ctx, manga)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.MangaEntity) error); ok {
		r1 = returnFunc(ctx, manga)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_IsNewerVersionAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNewerVersionAvailable'
type MockProvider_IsNewerVersionAvailable_Call struct {
	*mock.Call
}

// IsNewerVersionAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - manga domain.MangaEntity
func (_e *MockProvider_Expecter) IsNewerVersionAvailable(ctx interface{}, manga interface{}) *MockProvider_IsNewerVersionAvailable_Call {
	return &MockProvider_IsNewerVersionAvailable_Call{Call: _e.mock.On("IsNewerVersionAvailable", ctx, manga)}
}

func (_c *MockProvider_IsNewerVersionAvailable_Call) Run(run func(ctx context.Context, manga domain.MangaEntity)) *MockProvider_IsNewerVersionAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.MangaEntity
		if args[1] != nil {
			arg1 = args[1].(domain.MangaEntity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_IsNewerVersionAvailable_Call) Return(b bool, err error) *MockProvider_IsNewerVersionAvailable_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProvider_IsNewerVersionAvailable_Call) RunAndReturn(run func(ctx context.Context, manga domain.MangaEntity) (bool, error)) *MockProvider_IsNewerVersionAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Kind provides a mock function for the type MockProvider
func (_mock *MockProvider) Kind() domain.MangaSource {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 domain.MangaSource
	if returnFunc, ok := ret.Get(0).(func() domain.MangaSource); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.MangaSource)
	}
	return r0
}

// MockProvider_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type MockProvider_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Kind() *MockProvider_Kind_Call {
	return &MockProvider_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *MockProvider_Kind_Call) Run(run func()) *MockProvider_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Kind_Call) Return(mangaSource domain.MangaSource) *MockProvider_Kind_Call {
	_c.Call.Return(mangaSource)
	return _c
}

func (_c *MockProvider_Kind_Call) RunAndReturn(run func() domain.MangaSource) *MockProvider_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockProvider
func (_mock *MockProvider) Search(ctx context.Context, query string, offset int) ([]domain.SearchResult, int, error) {
	ret := _mock.Called(ctx, query, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.SearchResult
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.SearchResult, int, error)); ok {
		return returnFunc(ctx, query, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []domain.SearchResult); ok {
		r0 = returnFunc(ctx, query, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) int); ok {
		r1 = returnFunc(ctx, query, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = returnFunc(ctx, query, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProvider_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProvider_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - offset int
func (_e *MockProvider_Expecter) Search(ctx interface{}, query interface{}, offset interface{}) *MockProvider_Search_Call {
	return &MockProvider_Search_Call{Call: _e.mock.On("Search", ctx, query, offset)}
}

func (_c *MockProvider_Search_Call) Run(run func(ctx context.Context, query string, offset int)) *MockProvider_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_Search_Call) Return(searchResults []domain.SearchResult, n int, err error) *MockProvider_Search_Call {
	_c.Call.Return(searchResults, n, err)
	return _c
}

func (_c *MockProvider_Search_Call) RunAndReturn(run func(ctx context.Context, query string, offset int) ([]domain.SearchResult, int, error)) *MockProvider_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Supports provides a mock function for the type MockProvider
func (_mock *MockProvider) Supports(url string) bool {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Supports")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProvider_Supports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supports'
type MockProvider_Supports_Call struct {
	*mock.Call
}

// Supports is a helper method to define mock.On call
//   - url string
func (_e *MockProvider_Expecter) Supports(url interface{}) *MockProvider_Supports_Call {
	return &MockProvider_Supports_Call{Call: _e.mock.On("Supports", url)}
}

func (_c *MockProvider_Supports_Call) Run(run func(url string)) *MockProvider_Supports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_Supports_Call) Return(b bool) *MockProvider_Supports_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProvider_Supports_Call) RunAndReturn(run func(url string) bool) *MockProvider_Supports_Call {
	_c.Call.Return(run)
	return _c
}
