// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ivan-penchev/manga-updates/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AddManga provides a mock function for the type MockStore
func (_mock *MockStore) AddManga(ctx context.Context, manga domain.MangaEntity) error {
	ret := _mock.Called(ctx, manga)

	if len(ret) == 0 {
		panic("no return value specified for AddManga")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MangaEntity) error); ok {
		r0 = returnFunc(ctx, manga)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_AddManga_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddManga'
type MockStore_AddManga_Call struct {
	*mock.Call
}

// AddManga is a helper method to define mock.On call
//   - ctx context.Context
//   - manga domain.MangaEntity
func (_e *MockStore_Expecter) AddManga(ctx interface{}, manga interface{}) *MockStore_AddManga_Call {
	return &MockStore_AddManga_Call{Call: _e.mock.On("AddManga", ctx, manga)}
}

func (_c *MockStore_AddManga_Call) Run(run func(ctx context.Context, manga domain.MangaEntity)) *MockStore_AddManga_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.MangaEntity
		if args[1] != nil {
			arg1 = args[1].(domain.MangaEntity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_AddManga_Call) Return(err error) *MockStore_AddManga_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_AddManga_Call) RunAndReturn(run func(ctx context.Context, manga domain.MangaEntity) error) *MockStore_AddManga_Call {
	_c.Call.Return(run)
	return _c
}

// GetMangaSeries provides a mock function for the type MockStore
func (_mock *MockStore) GetMangaSeries(ctx context.Context) map[string]domain.MangaEntity {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMangaSeries")
	}

	var r0 map[string]domain.MangaEntity
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]domain.MangaEntity); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.MangaEntity)
		}
	}
	return r0
}

// MockStore_GetMangaSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMangaSeries'
type MockStore_GetMangaSeries_Call struct {
	*mock.Call
}

// GetMangaSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetMangaSeries(ctx interface{}) *MockStore_GetMangaSeries_Call {
	return &MockStore_GetMangaSeries_Call{Call: _e.mock.On("GetMangaSeries", ctx)}
}

func (_c *MockStore_GetMangaSeries_Call) Run(run func(ctx context.Context)) *MockStore_GetMangaSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetMangaSeries_Call) Return(stringToMangaEntity map[string]domain.MangaEntity) *MockStore_GetMangaSeries_Call {
	_c.Call.Return(stringToMangaEntity)
	return _c
}

func (_c *MockStore_GetMangaSeries_Call) RunAndReturn(run func(ctx context.Context) map[string]domain.MangaEntity) *MockStore_GetMangaSeries_Call {
	_c.Call.Return(run)
	return _c
}

// PersistMangaTitle provides a mock function for the type MockStore
func (_mock *MockStore) PersistMangaTitle(ctx context.Context, location string, mangaTitle domain.MangaEntity) error {
	ret := _mock.Called(ctx, location, mangaTitle)

	if len(ret) == 0 {
		panic("no return value specified for PersistMangaTitle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.MangaEntity) error); ok {
		r0 = returnFunc(ctx, location, mangaTitle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PersistMangaTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistMangaTitle'
type MockStore_PersistMangaTitle_Call struct {
	*mock.Call
}

// PersistMangaTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - location string
//   - mangaTitle domain.MangaEntity
func (_e *MockStore_Expecter) PersistMangaTitle(ctx interface{}, location interface{}, mangaTitle interface{}) *MockStore_PersistMangaTitle_Call {
	return &MockStore_PersistMangaTitle_Call{Call: _e.mock.On("PersistMangaTitle", ctx, location, mangaTitle)}
}

func (_c *MockStore_PersistMangaTitle_Call) Run(run func(ctx context.Context, location string, mangaTitle domain.MangaEntity)) *MockStore_PersistMangaTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.MangaEntity
		if args[2] != nil {
			arg2 = args[2].(domain.MangaEntity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_PersistMangaTitle_Call) Return(err error) *MockStore_PersistMangaTitle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PersistMangaTitle_Call) RunAndReturn(run func(ctx context.Context, location string, mangaTitle domain.MangaEntity) error) *MockStore_PersistMangaTitle_Call {
	_c.Call.Return(run)
	return _c
}
