// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/ivan-penchev/manga-updates/internal/domain"
)

// StoreMock is an autogenerated mock type for the Store type
type StoreMock struct {
	mock.Mock
}

type StoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreMock) EXPECT() *StoreMock_Expecter {
	return &StoreMock_Expecter{mock: &_m.Mock}
}

// GetMangaSeries provides a mock function with given fields: ctx
func (_m *StoreMock) GetMangaSeries(ctx context.Context) map[string]domain.MangaEntity {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMangaSeries")
	}

	var r0 map[string]domain.MangaEntity
	if rf, ok := ret.Get(0).(func(context.Context) map[string]domain.MangaEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.MangaEntity)
		}
	}

	return r0
}

// StoreMock_GetMangaSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMangaSeries'
type StoreMock_GetMangaSeries_Call struct {
	*mock.Call
}

// GetMangaSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StoreMock_Expecter) GetMangaSeries(ctx interface{}) *StoreMock_GetMangaSeries_Call {
	return &StoreMock_GetMangaSeries_Call{Call: _e.mock.On("GetMangaSeries", ctx)}
}

func (_c *StoreMock_GetMangaSeries_Call) Run(run func(ctx context.Context)) *StoreMock_GetMangaSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StoreMock_GetMangaSeries_Call) Return(_a0 map[string]domain.MangaEntity) *StoreMock_GetMangaSeries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StoreMock_GetMangaSeries_Call) RunAndReturn(run func(context.Context) map[string]domain.MangaEntity) *StoreMock_GetMangaSeries_Call {
	_c.Call.Return(run)
	return _c
}

// PersistManagaTitle provides a mock function with given fields: ctx, location, mangaTitle
func (_m *StoreMock) PersistManagaTitle(ctx context.Context, location string, mangaTitle domain.MangaEntity) error {
	ret := _m.Called(ctx, location, mangaTitle)

	if len(ret) == 0 {
		panic("no return value specified for PersistManagaTitle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.MangaEntity) error); ok {
		r0 = rf(ctx, location, mangaTitle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreMock_PersistManagaTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistManagaTitle'
type StoreMock_PersistManagaTitle_Call struct {
	*mock.Call
}

// PersistManagaTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - location string
//   - mangaTitle domain.MangaEntity
func (_e *StoreMock_Expecter) PersistManagaTitle(ctx interface{}, location interface{}, mangaTitle interface{}) *StoreMock_PersistManagaTitle_Call {
	return &StoreMock_PersistManagaTitle_Call{Call: _e.mock.On("PersistManagaTitle", ctx, location, mangaTitle)}
}

func (_c *StoreMock_PersistManagaTitle_Call) Run(run func(ctx context.Context, location string, mangaTitle domain.MangaEntity)) *StoreMock_PersistManagaTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.MangaEntity))
	})
	return _c
}

func (_c *StoreMock_PersistManagaTitle_Call) Return(_a0 error) *StoreMock_PersistManagaTitle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StoreMock_PersistManagaTitle_Call) RunAndReturn(run func(context.Context, string, domain.MangaEntity) error) *StoreMock_PersistManagaTitle_Call {
	_c.Call.Return(run)
	return _c
}

// NewStoreMock creates a new instance of StoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreMock {
	mock := &StoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
