dir: "internal/mocks/"
filename: "{{ .InterfaceName }}.go"
pkgname: "mocks"
packages:
  github.com/ivan-penchev/manga-updates/internal/store:
    interfaces:
      Store:
  github.com/ivan-penchev/manga-updates/internal/notifier:
    interfaces:
      Notifier:
  github.com/ivan-penchev/manga-updates/internal/domain:
    interfaces:
      Provider:
      ProviderRouter:
